#pragma once
enum Direction {TOP, LEFT, BOTTOM, RIGHT, NOT};
enum TileProperty {WALKABLE, DESTROYABLE, NOTHING, INEXISTANT, BOMB};
enum ITEM {BOMBPLUS, POWERPLUS, NOITEM};
enum COLOR {RED, GREEN, BLUE, YELLOW, ORANGE, BLACK, WHITE, PURPLE};